# Generated by Django 4.2.4 on 2023-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirtydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
